"""Numerical gear generation by the envelope (hobbing / rack-shaper) method.

Instead of evaluating the closed-form involute, this module *simulates the
manufacturing process*: a straight-sided rack cutter rolls without slipping on
the gear pitch circle and the tooth profile emerges as the inner envelope of
all cutter positions.  This reproduces the real machined shape, including the
**trochoidal root fillet** generated by the rounded cutter tip and the
**undercut** that appears on low tooth counts.

Method
------
For every roll angle ``phi`` the gear turns by ``phi`` while the rack shifts by
``rp*phi`` (pure rolling).  The cutting edge points are transformed into the
gear frame; the carved boundary at a polar angle ``theta`` is the *minimum*
radius any cutter-edge point reaches there over the whole roll.  Sampling one
pitch sector and replicating it ``z`` times yields the closed tooth profile.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import List, Tuple

Point = Tuple[float, float]


@dataclass
class GenerationResult:
    profile: List[Point]          # full closed CCW gear profile
    sector: List[Point]           # one pitch sector (r, theta) sampled
    undercut: bool                # True if undercut was detected
    root_radius: float
    tip_radius: float
    base_radius: float


def _cutter_edge(m: float, z: float, alpha: float, x: float,
                 ha: float, hf: float, tip_radius: float,
                 n_flank: int, n_tip: int) -> List[Point]:
    """Cutting edge of one rack-cutter tooth in rack coordinates.

    The rack pitch line is at ``x = rp``; +x points away from the gear centre,
    so the cutter tip (which cuts the gear root) is at the smallest x.  The two
    corners between each flank and the flat tip land carry a radius
    ``tip_radius`` - this is what cuts the trochoidal root fillet.
    """
    rp = m * z / 2.0
    ta = math.tan(alpha)
    w_roll = m * (math.pi / 4.0 - x * ta)   # half width on the rolling line
    x_tip = rp - (hf - x) * m               # gear root radius rf
    x_top = rp + (ha + x) * m               # gear tip radius ra

    def hw(xx: float) -> float:
        return w_roll + (xx - rp) * ta

    w_tip = hw(x_tip)
    rho = tip_radius if (tip_radius > 1e-6 and tip_radius < 0.9 * w_tip) else 0.0

    edge: List[Point] = []
    sq = math.sqrt(ta * ta + 1.0)

    if rho > 0.0:
        # Fillet centre tangent to the flank line and the tip land (x=x_tip).
        cx = x_tip + rho
        cy = rho * sq - ta * (x_tip + rho) - w_roll + rp * ta   # right (y<0)
        # tangent point on the flank: foot of perpendicular from centre.
        # flank line: ta*X + Y + (w_roll - rp*ta) = 0
        d = (ta * cx + cy + (w_roll - rp * ta)) / sq
        tfx = cx - d * ta / sq
        tfy = cy - d * 1.0 / sq
        a_flank = math.atan2(tfy - cy, tfx - cx)
        a_land = math.atan2(0.0 - cy, x_tip - cx)   # tangent on tip land
    else:
        cx = cy = 0.0

    # Right flank (y < 0): from gear-tip level down to the fillet tangent.
    end_x = x_tip if rho == 0 else tfx
    for i in range(n_flank + 1):
        xx = x_top + (end_x - x_top) * i / n_flank
        edge.append((xx, -hw(xx)))

    if rho > 0.0:
        # right corner arc (flank tangent -> tip land tangent)
        for i in range(n_tip + 1):
            a = a_flank + (a_land - a_flank) * i / n_tip
            edge.append((cx + rho * math.cos(a), cy + rho * math.sin(a)))
        # flat tip land across to the mirrored (left) corner
        edge.append((x_tip, cy))
        edge.append((x_tip, -cy))
        for i in range(n_tip + 1):       # left corner arc (mirror of right)
            a = a_flank + (a_land - a_flank) * i / n_tip
            edge.append((cx + rho * math.cos(a), -(cy + rho * math.sin(a))))
    else:
        edge.append((x_tip, -w_tip))
        edge.append((x_tip, w_tip))

    # Left flank (y > 0): fillet tangent up to gear-tip level.
    start_x = x_tip if rho == 0 else tfx
    for i in range(n_flank + 1):
        xx = start_x + (x_top - start_x) * i / n_flank
        edge.append((xx, hw(xx)))
    return edge


def generate_profile(m: float, z: int, pressure_angle: float = 20.0,
                     profile_shift: float = 0.0, addendum_coef: float = 1.0,
                     dedendum_coef: float = 1.25, tip_radius_coef: float = 0.38,
                     rolls: int = 600, bins: int = 240,
                     points_per_tooth: int = 60) -> GenerationResult:
    """Generate a gear tooth profile numerically by the rolling-rack envelope.

    The simulation uses ``bins`` per tooth for accuracy, then the sector is
    decimated to ``points_per_tooth`` points for a compact, CAD-friendly
    polygon (raise it for finer CNC paths)."""
    alpha = math.radians(pressure_angle)
    rp = m * z / 2.0
    rb = rp * math.cos(alpha)
    ra = rp + (addendum_coef + profile_shift) * m
    rf = rp - (dedendum_coef - profile_shift) * m
    tip_radius = tip_radius_coef * m

    edge = _cutter_edge(m, z, alpha, profile_shift, addendum_coef, dedendum_coef,
                        tip_radius, n_flank=60, n_tip=14)

    # Roll far enough to fully generate the flank up to the tip.
    a_tip = math.acos(max(-1.0, min(1.0, rb / ra)))
    phi_max = math.tan(a_tip) + math.pi / z + 0.2
    half = math.pi / z                       # half angular pitch

    INF = ra * 10.0
    rmin = [INF] * (bins + 1)                 # min radius per angular bin

    for j in range(rolls + 1):
        phi = -phi_max + 2.0 * phi_max * j / rolls
        s = rp * phi
        c, sn = math.cos(-phi), math.sin(-phi)
        for (qx, qy) in edge:
            # translate along rack, then rotate into the gear frame
            tx, ty = qx, qy + s
            gx = tx * c - ty * sn
            gy = tx * sn + ty * c
            r = math.hypot(gx, gy)
            if r > ra:
                continue
            th = math.atan2(gy, gx)
            if th < -half or th > half:
                continue
            b = int(round((th + half) / (2.0 * half) * bins))
            if 0 <= b <= bins and r < rmin[b]:
                rmin[b] = r

    # Build the sector R(theta); fill never-cut bins (the tooth top) with ra.
    sector: List[Point] = []
    for b in range(bins + 1):
        th = -half + 2.0 * half * b / bins
        r = rmin[b]
        if r >= INF:
            r = ra
        r = min(r, ra)
        r = max(r, rf - 1e-6)
        sector.append((r, th))

    # Undercut occurs when the cutter addendum reaches below the interference
    # point: z < 2(ha* - x) / sin^2(alpha)  (standard generation condition).
    z_min = 2.0 * (addendum_coef - profile_shift) / (math.sin(alpha) ** 2)
    undercut = z < z_min - 1e-9

    # Decimate the fine sector to a compact, CAD-friendly point count.
    npts = max(8, points_per_tooth)
    if len(sector) > npts:
        step = (len(sector) - 1) / npts
        sector = [sector[min(len(sector) - 1, int(round(i * step)))]
                  for i in range(npts + 1)]

    # Replicate the sector into a full closed CCW profile.
    profile: List[Point] = []
    for k in range(z):
        base = k * 2.0 * math.pi / z
        for (r, th) in sector[:-1]:           # drop duplicate seam point
            ang = base + th
            profile.append((r * math.cos(ang), r * math.sin(ang)))
    return GenerationResult(profile, sector, undercut, rf, ra, rb)


def generated_gear_profile(params, rolls: int = 600, bins: int = 240,
                           points_per_tooth: int = 60) -> List[Point]:
    """Numerically generated profile of ``params`` (a GearParams), returned in
    the same convention as :func:`geargen.geometry.gear_profile` (closed, CCW,
    a tooth centred on +x) so it is a drop-in for the transmissions."""
    from .geometry import polygon_area, rotate
    z = params.z
    m_t = params.module / math.cos(params.beta)        # transverse module
    res = generate_profile(m_t, z, math.degrees(params.alpha_t),
                           params.profile_shift, params.addendum_coef,
                           params.dedendum_coef, rolls=rolls, bins=bins,
                           points_per_tooth=points_per_tooth)
    # The sector is space-centred at 0; rotate by half a pitch to put a tooth
    # on +x (matching gear_profile's convention).
    off = math.pi / z
    prof = [rotate(p, off) for p in res.profile]
    if polygon_area(prof) < 0:
        prof.reverse()
    return prof
